# Generated by Django 4.2.5 on 2023-09-30 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_user', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('payment_data', models.JSONField(blank=True, null=True)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Bank_name', models.CharField(max_length=100)),
                ('transfer_payment', models.JSONField(blank=True, null=True)),
                ('bill_payment', models.JSONField(blank=True, null=True)),
                ('recipient_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='users.bankaccount')),
                ('sender_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='users.bankaccount')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transactiontype')),
            ],
        ),
    ]
