# Generated by Django 4.2.5 on 2023-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction_is_credit_transaction_is_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Bank_accountnumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Bank_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
