# Generated by Django 4.2.5 on 2023-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction_bank_accountnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
