# Generated by Django 4.2.5 on 2023-10-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bankaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(default=1234, max_length=4),
        ),
    ]
