# Generated by Django 4.2.5 on 2023-10-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_donetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('plans', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
