# Generated by Django 4.2.5 on 2023-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_atmcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
    ]
