# Generated by Django 4.2.5 on 2023-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='available_images/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
