# Generated by Django 4.2.5 on 2023-10-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_availableimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableimage',
            name='description',
        ),
    ]
