# Generated by Django 4.2.5 on 2023-10-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=11, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=90, null=True)),
                ('bank', models.CharField(blank=True, default='Vee Bank', max_length=90, null=True)),
                ('bank_code', models.CharField(blank=True, default='00', max_length=90, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
