# Generated by Django 4.2.5 on 2023-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_beneficary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficary',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficary',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
