# Generated by Django 4.2.5 on 2023-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_beneficary_is_external_beneficary_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='account_number',
            field=models.CharField(max_length=11),
        ),
    ]
